### ISSUE TITLE
 Not enough reads to assemble

### ISSUE THREAD

**Issue by dawnmy** [gFedonin/VirGenA#3]
I am using VirGenA with single-reference mode to assemble genomes from virus strain mixture. But it could not assemble some samples with the message "Not enough reads to assemble". I used the example config file and only changed the input, insert size and reference genome. Did I get something wrong?
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/497428/81809907-5d99ab00-9522-11ea-9acc-6b8a15e5eb66.png">

**Comment by gFedonin** [comment]
It looks like no reads were mapped to your reference. I believe this is due to small insert size you've provided! The "insert size" is actually maximal value of insert size for a pair of reads to be considered properly mapped. You can keep it large (1000 is default) or even increase if you want to allow mapping with even larger insert sizes.

**Comment by dawnmy** [comment]
Thank you for your prompt response. I tried to increase it to 2000 and still got the same message.

**Comment by gFedonin** [comment]
OK. My second guess is that your reference is lowercase (as I can see from the screenshot) and reads are uppercase. VirGenA is case sensitive :(

**Comment by dawnmy** [comment]
Ah It seems this was the culprit. Thank you so much!
